//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllamLütfen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MacFitEntities : DbContext
    {
        public MacFitEntities()
            : base("name=MacFitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egitmen> Egitmen { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<Get_MemberById_Result> Get_MemberById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_MemberById_Result>("Get_MemberById", idParameter);
        }
    
        public virtual ObjectResult<Get_user_Result> Get_user(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_user_Result>("Get_user", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Get_Instructors_Result> Get_Instructors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Instructors_Result>("Get_Instructors");
        }
    
        public virtual ObjectResult<Get_User_login_Result> Get_User_login(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_login_Result>("Get_User_login", emailParameter, passwordParameter);
        }
    
        public virtual int Uye_Kayıt(Nullable<int> id, string ad_Soyad, Nullable<System.DateTime> dogum_Tarihi, string email, string password, string locationAdress, string locationSehir)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ad_SoyadParameter = ad_Soyad != null ?
                new ObjectParameter("Ad_Soyad", ad_Soyad) :
                new ObjectParameter("Ad_Soyad", typeof(string));
    
            var dogum_TarihiParameter = dogum_Tarihi.HasValue ?
                new ObjectParameter("Dogum_Tarihi", dogum_Tarihi) :
                new ObjectParameter("Dogum_Tarihi", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var locationAdressParameter = locationAdress != null ?
                new ObjectParameter("LocationAdress", locationAdress) :
                new ObjectParameter("LocationAdress", typeof(string));
    
            var locationSehirParameter = locationSehir != null ?
                new ObjectParameter("LocationSehir", locationSehir) :
                new ObjectParameter("LocationSehir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Uye_Kayıt", idParameter, ad_SoyadParameter, dogum_TarihiParameter, emailParameter, passwordParameter, locationAdressParameter, locationSehirParameter);
        }
    }
}
